###### DB name
USER_TB='X_USER_TB'
COMPANY_TB='X_COMPANY_TB'
USER_COMPANY_TB='X_USER_COMPANY_TB'
CHANNEL_TB='X_CHANNEL_TB'
INTENT_TB='X_INTENT_TB'
ANSWER_TB='X_ANSWER_TB'
QUESTION_TB='X_QUESTION_TB'

APP_DB_PATH='/Users/kb/Desktop/NHC/projects/call/app/app.db'